using FomMon.Common.Shared;

namespace FomMon.Common.Configuration.Layer;

public sealed record LayerConfig(
    LayerKind Kind,
    string Name,
    string Description,
    string TableName, 
    string SourceIdColumn,
    string? WfsUrl,
    string? WfsLayer,
    string TileSource,
    string Color,
    string GeometryType,
    string Attribution)
{
    
    /// <summary>
    /// Table to create in DB.  Note, if it collides with OSM tables, the Martin autogenerated tilesource will have .1 appended.
    /// </summary>
    public string TableName { get; init; } = SqlUtil.ValidateSqlIdentifier(TableName);
    public string SourceIdColumn { get; init; } = SqlUtil.ValidateSqlIdentifier(SourceIdColumn);
}