using FomMon.Common.Shared;

namespace FomMon.Common.Configuration.Layer;

public enum Visibility
{
    Visible,
    Hidden,
}
public sealed record LayerColumnConfig(
    string Name,
    Visibility Visibility = Visibility.Visible,
    string Decode = ""
)
{
}

public sealed record LayerConfig(
    LayerKind Kind,
    string Name,
    string FeatureName,
    string Description,
    string TableName, 
    string SourceIdColumn,
    string? WfsUrl,
    string? WfsLayer,
    string TileSource,
    string Color,
    string GeometryType,
    string Attribution,
    LayerColumnConfig[] Columns)
{
    
    /// <summary>
    /// Table to create in DB.  Note, if it collides with OSM tables, the Martin autogenerated tilesource will have .1 appended.
    /// </summary>
    public string TableName { get; init; } = SqlUtil.ValidateSqlIdentifier(TableName);
    public string SourceIdColumn { get; init; } = SqlUtil.ValidateSqlIdentifier(SourceIdColumn);
}