using Microsoft.EntityFrameworkCore;

namespace FomMon.Data.Infrastructure;

public class PostgresReservedKeywordValidator
{
    private static readonly HashSet<string> PostgresReservedKeywords = new(StringComparer.OrdinalIgnoreCase)
    {
    "A", "ABS", "ACCORDING", "ACOS", "ADA", "ALL", "ALLOCATE", "ANALYSE", "ANALYZE", "AND", "ANY", "ANY_VALUE", "ARE",
    "ARRAY", "ARRAY_AGG", "ARRAY_MAX_CARDINALITY", "AS", "ASC", "ASIN", "ASYMMETRIC", "ATAN", "ATTRIBUTES",
    "AUTHORIZATION", "AVG", "BASE64", "BEGIN_FRAME", "BEGIN_PARTITION", "BERNOULLI", "BINARY", "BIT_LENGTH", "BLOB",
    "BLOCKED", "BOM", "BOTH", "BTRIM", "C", "CARDINALITY", "CASE", "CAST", "CATALOG_NAME", "CEIL", "CEILING",
    "CHAINING", "CHAR", "CHARACTER", "CHARACTERS", "CHARACTER_LENGTH", "CHARACTER_SET_CATALOG", "CHARACTER_SET_NAME",
    "CHARACTER_SET_SCHEMA", "CHAR_LENGTH", "CHECK", "CLASSIFIER", "CLASS_ORIGIN", "CLOB", "COBOL", "COLLATE",
    "COLLATION", "COLLATION_CATALOG", "COLLATION_NAME", "COLLATION_SCHEMA", "COLLECT", "COLUMN", "COLUMN_NAME",
    "COMMAND_FUNCTION", "COMMAND_FUNCTION_CODE", "CONCURRENTLY", "CONDITION", "CONDITION_NUMBER", "CONNECT",
    "CONNECTION_NAME", "CONSTRAINT", "CONSTRAINT_CATALOG", "CONSTRAINT_NAME", "CONSTRAINT_SCHEMA", "CONSTRUCTOR",
    "CONTAINS", "CONTROL", "CONVERT", "COPARTITION", "CORR", "CORRESPONDING", "COS", "COSH", "COUNT", "COVAR_POP",
    "COVAR_SAMP", "CREATE", "CROSS", "CUME_DIST", "CURRENT_CATALOG", "CURRENT_DATE", "CURRENT_DEFAULT_TRANSFORM_GROUP",
    "CURRENT_PATH", "CURRENT_ROLE", "CURRENT_ROW", "CURRENT_SCHEMA", "CURRENT_TIME", "CURRENT_TIMESTAMP",
    "CURRENT_TRANSFORM_GROUP_FOR_TYPE", "CURRENT_USER", "CURSOR_NAME", "DATALINK", "DATE", "DATETIME_INTERVAL_CODE",
    "DATETIME_INTERVAL_PRECISION", "DAY", "DB", "DECFLOAT", "DEFAULT", "DEFERRABLE", "DEFINE", "DEFINED", "DEGREE",
    "DENSE_RANK", "DEREF", "DERIVED", "DESC", "DESCRIBE", "DESCRIPTOR", "DETERMINISTIC", "DIAGNOSTICS", "DISCONNECT",
    "DISPATCH", "DISTINCT", "DLNEWCOPY", "DLPREVIOUSCOPY", "DLURLCOMPLETE", "DLURLCOMPLETEONLY", "DLURLCOMPLETEWRITE",
    "DLURLPATH", "DLURLPATHONLY", "DLURLPATHWRITE", "DLURLSCHEME", "DLURLSERVER", "DLVALUE", "DO", "DYNAMIC",
    "DYNAMIC_FUNCTION", "DYNAMIC_FUNCTION_CODE", "ELEMENT", "ELSE", "END", "END-EXEC", "END_FRAME", "END_PARTITION",
    "EQUALS", "EVERY", "EXCEPT", "EXCEPTION", "EXEC", "EXP", "FALSE", "FETCH", "FILE", "FILTER", "FINAL", "FINISH",
    "FIRST_VALUE", "FLAG", "FLOOR", "FOR", "FOREIGN", "FORTRAN", "FOUND", "FRAME_ROW", "FREE", "FREEZE", "FROM", "FS",
    "FULFILL", "FULL", "FUSION", "G", "GENERAL", "GET", "GO", "GOTO", "GRANT", "GROUP", "HAVING", "HEX", "HIERARCHY",
    "HOUR", "IGNORE", "ILIKE", "IMMEDIATELY", "IMPLEMENTATION", "IN", "INDICATOR", "INITIAL", "INITIALLY",
    "INNER", "INSTANCE", "INSTANTIABLE", "INTEGRITY", "INTERSECT", "INTERSECTION", "INTO", "IS", "ISNULL", "JOIN",
    "JSON_TABLE_PRIMITIVE", "K", "KEY_MEMBER", "KEY_TYPE", "LAG", "LAST_VALUE", "LATERAL", "LEAD", "LEADING", "LEFT",
    "LENGTH", "LIBRARY", "LIKE", "LIKE_REGEX", "LIMIT", "LINK", "LISTAGG", "LN", "LOCALTIME", "LOCALTIMESTAMP",
    "LOCATOR", "LOG", "LOG10", "LOWER", "LPAD", "LTRIM", "M", "MAP", "MATCHES", "MATCH_NUMBER", "MATCH_RECOGNIZE",
    "MAX", "MEASURES", "MEMBER", "MESSAGE_LENGTH", "MESSAGE_OCTET_LENGTH", "MESSAGE_TEXT", "MIN", "MINUTE", "MOD",
    "MODIFIES", "MODULE", "MONTH", "MORE", "MULTISET", "MUMPS", "NAMESPACE", "NATURAL", "NCLOB", "NESTING", "NIL",
    "NOT", "NOTNULL", "NTH_VALUE", "NTILE", "NULL", "NULLABLE", "NULL_ORDERING", "NUMBER", "OCCURRENCE",
    "OCCURRENCES_REGEX", "OCTETS", "OCTET_LENGTH", "OFFSET", "ON", "ONE", "ONLY", "OPEN", "OR", "ORDER", "ORDERING",
    "OUTER", "OUTPUT", "OVER", "OVERFLOW", "OVERLAPS", "P", "PAD", "PARAMETER_MODE", "PARAMETER_NAME",
    "PARAMETER_ORDINAL_POSITION", "PARAMETER_SPECIFIC_CATALOG", "PARAMETER_SPECIFIC_NAME", "PARAMETER_SPECIFIC_SCHEMA",
    "PASCAL", "PASS", "PASSTHROUGH", "PAST", "PATTERN", "PER", "PERCENT", "PERCENTILE_CONT", "PERCENTILE_DISC",
    "PERCENT_RANK", "PERMISSION", "PERMUTE", "PIPE", "PLACING", "PLI", "PORTION", "POSITION_REGEX", "POWER", "PRECEDES",
    "PRECISION", "PREV", "PRIMARY", "PRIVATE", "PRUNE", "PTF", "PUBLIC", "RANK", "READS", "RECOVERY", "REFERENCES",
    "REGR_AVGX", "REGR_AVGY", "REGR_COUNT", "REGR_INTERCEPT", "REGR_R2", "REGR_SLOPE", "REGR_SXX", "REGR_SXY",
    "REGR_SYY", "REQUIRING", "RESPECT", "RESTORE", "RESULT", "RETURNED_CARDINALITY", "RETURNED_LENGTH",
    "RETURNED_OCTET_LENGTH", "RETURNED_SQLSTATE", "RETURNING", "RIGHT", "ROUTINE_CATALOG", "ROUTINE_NAME",
    "ROUTINE_SCHEMA", "ROW_COUNT", "ROW_NUMBER", "RPAD", "RTRIM", "RUNNING", "SCALE", "SCHEMA_NAME", "SCOPE",
    "SCOPE_CATALOG", "SCOPE_NAME", "SCOPE_SCHEMA", "SECOND", "SECTION", "SEEK", "SELECT", "SELECTIVE", "SELF",
    "SEMANTICS", "SENSITIVE", "SERVER_NAME", "SESSION_USER", "SIMILAR", "SIN", "SINH", "SIZE", "SOME", "SORT_DIRECTION",
    "SPACE", "SPECIFIC", "SPECIFICTYPE", "SPECIFIC_NAME", "SQLCODE", "SQLERROR", "SQLEXCEPTION", "SQLSTATE",
    "SQLWARNING", "SQRT", "STATIC", "STDDEV_POP", "STDDEV_SAMP", "STRUCTURE", "STYLE", "SUBCLASS_ORIGIN",
    "SUBMULTISET", "SUBSET", "SUBSTRING_REGEX", "SUCCEEDS", "SUM", "SYMMETRIC", "SYSTEM_TIME", "SYSTEM_USER", "T",
    "TABLE", "TABLESAMPLE", "TABLE_NAME", "TAN", "TANH", "THEN", "THROUGH", "TIMEZONE_HOUR", "TIMEZONE_MINUTE", "TO",
    "TOKEN", "TOP_LEVEL_COUNT", "TRAILING", "TRANSACTIONS_COMMITTED", "TRANSACTIONS_ROLLED_BACK", "TRANSACTION_ACTIVE",
    "TRANSFORMS", "TRANSLATE", "TRANSLATE_REGEX", "TRANSLATION", "TRIGGER_CATALOG", "TRIGGER_NAME", "TRIGGER_SCHEMA",
    "TRIM_ARRAY", "TRUE", "UNDER", "UNION", "UNIQUE", "UNLINK", "UNMATCHED", "UNNAMED", "UNNEST", "UNTYPED", "UPPER",
    "URI", "USAGE", "USER", "USER_DEFINED_TYPE_CATALOG", "USER_DEFINED_TYPE_CODE", "USER_DEFINED_TYPE_NAME",
    "USER_DEFINED_TYPE_SCHEMA", "USING", "UTF16", "UTF32", "UTF8", "VALUE_OF", "VARBINARY", "VARIADIC", "VARYING",
    "VAR_POP", "VAR_SAMP", "VERBOSE", "VERSIONING", "WHEN", "WHENEVER", "WHERE", "WIDTH_BUCKET", "WINDOW", "WITH",
    "WITHIN", "WITHOUT", "XMLAGG", "XMLBINARY", "XMLCAST", "XMLCOMMENT", "XMLDECLARATION", "XMLDOCUMENT", "XMLITERATE",
    "XMLQUERY", "XMLSCHEMA", "XMLTEXT", "XMLVALIDATE", "YEAR"
    // technically reserved but actually fine...: "ID", "STATE"
    };

    public static void ValidateModel(ModelBuilder modelBuilder)
    {
        foreach (var entityType in modelBuilder.Model.GetEntityTypes())
        {
            foreach (var property in entityType.GetProperties())
            {
                var columnName = property.GetColumnName();
                if (PostgresReservedKeywords.Contains(columnName))
                {
                    throw new InvalidOperationException(
                        $"Property '{property.Name}' in entity '{entityType.ClrType.Name}' " +
                        $"maps to reserved PostgreSQL keyword '{columnName}'. ");
                }
            }
        }
    }
}